name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build

    - name: Move Prisma Schema
      run: |
        mkdir -p dist/prisma
        cp prisma/schema.prisma dist/prisma/schema.prisma

    - name: Copy Additional Files
      run: |
        cp package.json dist/package.json
        mkdir -p dist/src/templates
        cp -r src/templates/* dist/src/templates/
        mkdir -p dist/src/locales
        cp -r src/locales/* dist/src/locales/

    - name: Upload to cPanel
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USER }}
        password: ${{ secrets.CPANEL_PASS }}
        port: 21098
        source: dist/*
        target: /home/techdcbn/dev-dash-takhawe.hayah.tech/

    - name: Execute Post-Upload Commands
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USER }}
        password: ${{ secrets.CPANEL_PASS }}
        port: 21098
        script: |
          # Move contents from /dist to /
          cp -a /home/techdcbn/dev-dash-takhawe.hayah.tech/dist/* /home/techdcbn/dev-dash-takhawe.hayah.tech/
          
          # Remove the now-empty dist directory
          rm -rf /home/techdcbn/dev-dash-takhawe.hayah.tech/dist